### ISSUE TITLE
Auto include all transitive dependencies? 

### ISSUE THREAD

**Issue by Insadem** [teroneko/Teronis.DotNet#26]
Your solution is great, but It would be even better if transitive dependencies were a thing.
I know that you [aware](https://stackoverflow.com/questions/64581457/generating-nuget-package-on-build-does-not-include-all-dependencies) about it, but I wonder why there's no solution for this.
Is it hard to make? I would like to make it, but I don't know much about net tools.

**Comment by teneko** [comment]
Simply said, yes. Long story: The problem is the that there is too much to consider to make a generic solution. You can compare it with [npm](https://www.beyondjava.net/npm-transitive-dependencies), so you would need to spin your head around to make it work. Another point, I have worked already on a solution that, well, is not very user friendly and not very reliable. So yes, it is hard to make.

**Comment by Insadem** [comment]
> Simply said, yes. Long story: The problem is the that there is too much to consider to make a generic solution. You can compare it with [npm](https://www.beyondjava.net/npm-transitive-dependencies), so you would need to spin your head around to make it work. Another point, I have worked already on a solution that, well, is not very user friendly and not very reliable. So yes, it is hard to make.

It's sad. My problem is that I use multiple projects in one solution, so project reference is the best option for me. I tried to use local nuget packages, but It's actually hell for constantly updating local projects. I need always change version, otherwise packages are cached. Did you found solution for this type of problem?

**Comment by teneko** [comment]
You then simply should [delete the cache](https://learn.microsoft.com/de-de/nuget/hosting-packages/local-feeds). Or you write a program to delete the cache. By using my [NuGetRunner](https://github.com/vernuntii/vernuntii/blob/75e1e7f4b05276202a3ef1adceb180219380b721/src/Vernuntii.Console.GlobalTool.Generic/DotNet/NuGetRunner.cs) (please respect license), you can get the cache directory to your local package, that you can then delete, but it would be tricky to make this automatic. I think you simply use GitVersion to auto-increment your version for each new commit you make (called continous deployment).

Edit: another fun idea is to set your package version to something like this `<PackageVersion>0.0.1-$([System.Guid]::NewGuid())</PackageVersion>` while only working local of course. 😄
