### ISSUE TITLE
Your documentation website domain is offline, documentation is not available

### ISSUE THREAD

**Issue by jeffward01** [teroneko/Teronis.DotNet#29]
Very cool project!!! This is incredibly handy, and should be a very popular project! Thank you for this!!

## Issue
I was trying to explore the documentation, and it appears to be offline: https://teroneko.de/docs/Teronis.DotNet/Microsoft.Extensions.DependencyInjection.html

if you have some time to look into this, that would be great. 
at community members like myself can contribute to the wiki documentation as well.

### Suggestion:

To offload some of the maintenance of the `dos` and `wiki` to community members , which gives people like myself the ability to  contribute to the wiki documentation as well,  I suggest:

* Using `.md` files instead of a website, or use both
   * `.md` files are not as pretty, but much easier to expand and work with
* Use the built-in `Wiki` feature of GitHub

 

Thanks again!

**Comment by teneko** [comment]
Hey, glad to hear you are interessed in my source code. Here the new link: https://teneko.de/docs/Teronis.DotNet/Microsoft.Extensions.DependencyInjection.html

I changed my name from Teroneko to Teneko. 🙌

The website is completely auto-generated by https://github.com/teneko/teneko.github.io. Feel free to check it out.
