### ISSUE TITLE
.aar files from dependent android binding libs are not included in the nuget pack

### ISSUE THREAD

**Issue by AdamDiament** [teroneko/Teronis.DotNet#30]
My project is a .net 7 android binding lib, which depends on two other binding projects (ZoomCommonLib and Lottie.Android) 

I'd like to create a single nuget package without having to bother with nugets for the two dependent projects. So your project is ideal.
However the .aars are not brought over. Since XF => MAUI, .jars must now appear in the same directory as dlls, as they are no longer embedded in the .dll (source - https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects)

Nuget reference setup:

```xml
  <PackageReference Include="Teronis.MSBuild.Packaging.ProjectBuildInPackage" Version="1.0.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  ```

  Project reference section:

```xml
  <ItemGroup>
    <ProjectReference Include="..\Lottie.Android\Lottie.Android.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\ZoomCommonLib.MAUI\ZoomCommonLib.MAUI.csproj" PrivateAssets="all" />
  </ItemGroup>
```

Resulting Nuget package explorer - dlls from the dependent projects are brought in correctly, but the .aars are missing

![image](https://github.com/teneko/Teronis.DotNet/assets/6513834/5274cf60-c152-4a16-94bd-eb17bdab3750)

Can .aars be brought in as standard, or is there an option to include them in IncludeAssets?

Changing to 

` <IncludeAssets>all</IncludeAssets>`

Did not change anything.

**Comment by teneko** [comment]
I got you.

Your problem has nothing to with  Teronis.MSBuild.Packaging.ProjectBuildInPackage. You need to add custom files always manually. This is so by default.

To add custom files you can use either thr TFM-agnostic approach:
https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-file-without-an-extension
or the TFM-specific approach:
https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificcontentinpackage

You want the last.

**Comment by AdamDiament** [comment]
Nice one @teneko
