### ISSUE TITLE
Move ILoggerExtensions to friendly namespace

### ISSUE THREAD

**Issue by BrunoZell** [teroneko/Teronis.DotNet#6]
The class defined in _src/NetCoreApp/Identity/Identity/src/Extensions/ILoggerExtensions.cs_ has a namespace declared as `Microsoft.Extensions.Logging`. This leads to an ambiguous extension method reference and with that introduces a compile time error. The the official extension method with the same signature is defined in the same namespace.

Please consider moving the extension methods of this project into the exclusive namespace for this project so the consumers can choose what methods they want to use.

Version used: 0.1.7-alpha.17

**Comment by teroneko** [comment]
The the official extension method with the same signature you are telling from is defined in the same namespace by me. While splitting the origin project I forgot to delete that tiny class. Thanks for your detailed issue description.

**Comment by teroneko** [comment]
The official extension method with the same signature you are telling from is defined in the same namespace by me. While splitting the origin project I forgot to delete that tiny class so it resulted in named exception you faced. Thanks for your detailed issue description.

**Comment by BrunoZell** [comment]
Ah, I see. I wasn't sure what other method had the same signature because Visual Studio could only navigate to one of them 😄
